# Generated by Django 3.2.15 on 2022-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("ip", "post"), name="unique rating"
            ),
        ),
    ]
